/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class TFetchResultsResp : TBase
{
  private bool _hasMoreRows;
  private TRowSet _results;

  public TStatus Status { get; set; }

  public bool HasMoreRows
  {
    get
    {
      return _hasMoreRows;
    }
    set
    {
      __isset.hasMoreRows = true;
      this._hasMoreRows = value;
    }
  }

  public TRowSet Results
  {
    get
    {
      return _results;
    }
    set
    {
      __isset.@results = true;
      this._results = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool hasMoreRows;
    public bool @results;
  }

  public TFetchResultsResp()
  {
  }

  public TFetchResultsResp(TStatus @status) : this()
  {
    this.Status = @status;
  }

  public TFetchResultsResp DeepCopy()
  {
    var tmp485 = new TFetchResultsResp()
    if((Status != null))
    {
      tmp485.Status = (TStatus)this.Status.DeepCopy();
    }
    if(__isset.hasMoreRows)
    {
      tmp485.HasMoreRows = this.HasMoreRows;
    }
    tmp485.__isset.hasMoreRows = this.__isset.hasMoreRows;
    if((Results != null) && __isset.@results)
    {
      tmp485.Results = (TRowSet)this.Results.DeepCopy();
    }
    tmp485.__isset.@results = this.__isset.@results;
    return tmp485;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_status = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              Status = new TStatus();
              await Status.ReadAsync(iprot, cancellationToken);
              isset_status = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.Bool)
            {
              HasMoreRows = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.Struct)
            {
              Results = new TRowSet();
              await Results.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_status)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp486 = new TStruct("TFetchResultsResp");
      await oprot.WriteStructBeginAsync(tmp486, cancellationToken);
      var tmp487 = new TField();
      if((Status != null))
      {
        tmp487.Name = "status";
        tmp487.Type = TType.Struct;
        tmp487.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp487, cancellationToken);
        await Status.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.hasMoreRows)
      {
        tmp487.Name = "hasMoreRows";
        tmp487.Type = TType.Bool;
        tmp487.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp487, cancellationToken);
        await oprot.WriteBoolAsync(HasMoreRows, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Results != null) && __isset.@results)
      {
        tmp487.Name = "results";
        tmp487.Type = TType.Struct;
        tmp487.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp487, cancellationToken);
        await Results.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is TFetchResultsResp other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(Status, other.Status)
      && ((__isset.hasMoreRows == other.__isset.hasMoreRows) && ((!__isset.hasMoreRows) || (global::System.Object.Equals(HasMoreRows, other.HasMoreRows))))
      && ((__isset.@results == other.__isset.@results) && ((!__isset.@results) || (global::System.Object.Equals(Results, other.Results))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((Status != null))
      {
        hashcode = (hashcode * 397) + Status.GetHashCode();
      }
      if(__isset.hasMoreRows)
      {
        hashcode = (hashcode * 397) + HasMoreRows.GetHashCode();
      }
      if((Results != null) && __isset.@results)
      {
        hashcode = (hashcode * 397) + Results.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp488 = new StringBuilder("TFetchResultsResp(");
    if((Status != null))
    {
      tmp488.Append(", Status: ");
      Status.ToString(tmp488);
    }
    if(__isset.hasMoreRows)
    {
      tmp488.Append(", HasMoreRows: ");
      HasMoreRows.ToString(tmp488);
    }
    if((Results != null) && __isset.@results)
    {
      tmp488.Append(", Results: ");
      Results.ToString(tmp488);
    }
    tmp488.Append(')');
    return tmp488.ToString();
  }
}

