/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class TGetDelegationTokenReq : TBase
{

  public TSessionHandle SessionHandle { get; set; }

  public string Owner { get; set; }

  public string Renewer { get; set; }

  public TGetDelegationTokenReq()
  {
  }

  public TGetDelegationTokenReq(TSessionHandle sessionHandle, string @owner, string @renewer) : this()
  {
    this.SessionHandle = sessionHandle;
    this.Owner = @owner;
    this.Renewer = @renewer;
  }

  public TGetDelegationTokenReq DeepCopy()
  {
    var tmp490 = new TGetDelegationTokenReq()
    if((SessionHandle != null))
    {
      tmp490.SessionHandle = (TSessionHandle)this.SessionHandle.DeepCopy();
    }
    if((Owner != null))
    {
      tmp490.Owner = this.Owner;
    }
    if((Renewer != null))
    {
      tmp490.Renewer = this.Renewer;
    }
    return tmp490;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_sessionHandle = false;
      bool isset_owner = false;
      bool isset_renewer = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              SessionHandle = new TSessionHandle();
              await SessionHandle.ReadAsync(iprot, cancellationToken);
              isset_sessionHandle = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              Owner = await iprot.ReadStringAsync(cancellationToken);
              isset_owner = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              Renewer = await iprot.ReadStringAsync(cancellationToken);
              isset_renewer = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_sessionHandle)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_owner)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_renewer)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp491 = new TStruct("TGetDelegationTokenReq");
      await oprot.WriteStructBeginAsync(tmp491, cancellationToken);
      var tmp492 = new TField();
      if((SessionHandle != null))
      {
        tmp492.Name = "sessionHandle";
        tmp492.Type = TType.Struct;
        tmp492.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp492, cancellationToken);
        await SessionHandle.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Owner != null))
      {
        tmp492.Name = "owner";
        tmp492.Type = TType.String;
        tmp492.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp492, cancellationToken);
        await oprot.WriteStringAsync(Owner, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Renewer != null))
      {
        tmp492.Name = "renewer";
        tmp492.Type = TType.String;
        tmp492.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp492, cancellationToken);
        await oprot.WriteStringAsync(Renewer, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is TGetDelegationTokenReq other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(SessionHandle, other.SessionHandle)
      && global::System.Object.Equals(Owner, other.Owner)
      && global::System.Object.Equals(Renewer, other.Renewer);
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((SessionHandle != null))
      {
        hashcode = (hashcode * 397) + SessionHandle.GetHashCode();
      }
      if((Owner != null))
      {
        hashcode = (hashcode * 397) + Owner.GetHashCode();
      }
      if((Renewer != null))
      {
        hashcode = (hashcode * 397) + Renewer.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp493 = new StringBuilder("TGetDelegationTokenReq(");
    if((SessionHandle != null))
    {
      tmp493.Append(", SessionHandle: ");
      SessionHandle.ToString(tmp493);
    }
    if((Owner != null))
    {
      tmp493.Append(", Owner: ");
      Owner.ToString(tmp493);
    }
    if((Renewer != null))
    {
      tmp493.Append(", Renewer: ");
      Renewer.ToString(tmp493);
    }
    tmp493.Append(')');
    return tmp493.ToString();
  }
}

