/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class TGetInfoResp : TBase
{

  public TStatus Status { get; set; }

  public TGetInfoValue InfoValue { get; set; }

  public TGetInfoResp()
  {
  }

  public TGetInfoResp(TStatus @status, TGetInfoValue infoValue) : this()
  {
    this.Status = @status;
    this.InfoValue = infoValue;
  }

  public TGetInfoResp DeepCopy()
  {
    var tmp301 = new TGetInfoResp()
    if((Status != null))
    {
      tmp301.Status = (TStatus)this.Status.DeepCopy();
    }
    if((InfoValue != null))
    {
      tmp301.InfoValue = (TGetInfoValue)this.InfoValue.DeepCopy();
    }
    return tmp301;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_status = false;
      bool isset_infoValue = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              Status = new TStatus();
              await Status.ReadAsync(iprot, cancellationToken);
              isset_status = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.Struct)
            {
              InfoValue = new TGetInfoValue();
              await InfoValue.ReadAsync(iprot, cancellationToken);
              isset_infoValue = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_status)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_infoValue)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp302 = new TStruct("TGetInfoResp");
      await oprot.WriteStructBeginAsync(tmp302, cancellationToken);
      var tmp303 = new TField();
      if((Status != null))
      {
        tmp303.Name = "status";
        tmp303.Type = TType.Struct;
        tmp303.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp303, cancellationToken);
        await Status.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((InfoValue != null))
      {
        tmp303.Name = "infoValue";
        tmp303.Type = TType.Struct;
        tmp303.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp303, cancellationToken);
        await InfoValue.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is TGetInfoResp other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(Status, other.Status)
      && global::System.Object.Equals(InfoValue, other.InfoValue);
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((Status != null))
      {
        hashcode = (hashcode * 397) + Status.GetHashCode();
      }
      if((InfoValue != null))
      {
        hashcode = (hashcode * 397) + InfoValue.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp304 = new StringBuilder("TGetInfoResp(");
    if((Status != null))
    {
      tmp304.Append(", Status: ");
      Status.ToString(tmp304);
    }
    if((InfoValue != null))
    {
      tmp304.Append(", InfoValue: ");
      InfoValue.ToString(tmp304);
    }
    tmp304.Append(')');
    return tmp304.ToString();
  }
}

