/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class TGetColumnsReq : TBase
{
  private string _catalogName;
  private string _schemaName;
  private string _tableName;
  private string _columnName;

  public TSessionHandle SessionHandle { get; set; }

  public string CatalogName
  {
    get
    {
      return _catalogName;
    }
    set
    {
      __isset.catalogName = true;
      this._catalogName = value;
    }
  }

  public string SchemaName
  {
    get
    {
      return _schemaName;
    }
    set
    {
      __isset.schemaName = true;
      this._schemaName = value;
    }
  }

  public string TableName
  {
    get
    {
      return _tableName;
    }
    set
    {
      __isset.tableName = true;
      this._tableName = value;
    }
  }

  public string ColumnName
  {
    get
    {
      return _columnName;
    }
    set
    {
      __isset.columnName = true;
      this._columnName = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool catalogName;
    public bool schemaName;
    public bool tableName;
    public bool columnName;
  }

  public TGetColumnsReq()
  {
  }

  public TGetColumnsReq(TSessionHandle sessionHandle) : this()
  {
    this.SessionHandle = sessionHandle;
  }

  public TGetColumnsReq DeepCopy()
  {
    var tmp400 = new TGetColumnsReq()
    if((SessionHandle != null))
    {
      tmp400.SessionHandle = (TSessionHandle)this.SessionHandle.DeepCopy();
    }
    if((CatalogName != null) && __isset.catalogName)
    {
      tmp400.CatalogName = this.CatalogName;
    }
    tmp400.__isset.catalogName = this.__isset.catalogName;
    if((SchemaName != null) && __isset.schemaName)
    {
      tmp400.SchemaName = this.SchemaName;
    }
    tmp400.__isset.schemaName = this.__isset.schemaName;
    if((TableName != null) && __isset.tableName)
    {
      tmp400.TableName = this.TableName;
    }
    tmp400.__isset.tableName = this.__isset.tableName;
    if((ColumnName != null) && __isset.columnName)
    {
      tmp400.ColumnName = this.ColumnName;
    }
    tmp400.__isset.columnName = this.__isset.columnName;
    return tmp400;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_sessionHandle = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              SessionHandle = new TSessionHandle();
              await SessionHandle.ReadAsync(iprot, cancellationToken);
              isset_sessionHandle = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              CatalogName = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              SchemaName = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.String)
            {
              TableName = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.String)
            {
              ColumnName = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_sessionHandle)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp401 = new TStruct("TGetColumnsReq");
      await oprot.WriteStructBeginAsync(tmp401, cancellationToken);
      var tmp402 = new TField();
      if((SessionHandle != null))
      {
        tmp402.Name = "sessionHandle";
        tmp402.Type = TType.Struct;
        tmp402.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp402, cancellationToken);
        await SessionHandle.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CatalogName != null) && __isset.catalogName)
      {
        tmp402.Name = "catalogName";
        tmp402.Type = TType.String;
        tmp402.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp402, cancellationToken);
        await oprot.WriteStringAsync(CatalogName, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((SchemaName != null) && __isset.schemaName)
      {
        tmp402.Name = "schemaName";
        tmp402.Type = TType.String;
        tmp402.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp402, cancellationToken);
        await oprot.WriteStringAsync(SchemaName, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((TableName != null) && __isset.tableName)
      {
        tmp402.Name = "tableName";
        tmp402.Type = TType.String;
        tmp402.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp402, cancellationToken);
        await oprot.WriteStringAsync(TableName, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((ColumnName != null) && __isset.columnName)
      {
        tmp402.Name = "columnName";
        tmp402.Type = TType.String;
        tmp402.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp402, cancellationToken);
        await oprot.WriteStringAsync(ColumnName, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is TGetColumnsReq other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(SessionHandle, other.SessionHandle)
      && ((__isset.catalogName == other.__isset.catalogName) && ((!__isset.catalogName) || (global::System.Object.Equals(CatalogName, other.CatalogName))))
      && ((__isset.schemaName == other.__isset.schemaName) && ((!__isset.schemaName) || (global::System.Object.Equals(SchemaName, other.SchemaName))))
      && ((__isset.tableName == other.__isset.tableName) && ((!__isset.tableName) || (global::System.Object.Equals(TableName, other.TableName))))
      && ((__isset.columnName == other.__isset.columnName) && ((!__isset.columnName) || (global::System.Object.Equals(ColumnName, other.ColumnName))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((SessionHandle != null))
      {
        hashcode = (hashcode * 397) + SessionHandle.GetHashCode();
      }
      if((CatalogName != null) && __isset.catalogName)
      {
        hashcode = (hashcode * 397) + CatalogName.GetHashCode();
      }
      if((SchemaName != null) && __isset.schemaName)
      {
        hashcode = (hashcode * 397) + SchemaName.GetHashCode();
      }
      if((TableName != null) && __isset.tableName)
      {
        hashcode = (hashcode * 397) + TableName.GetHashCode();
      }
      if((ColumnName != null) && __isset.columnName)
      {
        hashcode = (hashcode * 397) + ColumnName.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp403 = new StringBuilder("TGetColumnsReq(");
    if((SessionHandle != null))
    {
      tmp403.Append(", SessionHandle: ");
      SessionHandle.ToString(tmp403);
    }
    if((CatalogName != null) && __isset.catalogName)
    {
      tmp403.Append(", CatalogName: ");
      CatalogName.ToString(tmp403);
    }
    if((SchemaName != null) && __isset.schemaName)
    {
      tmp403.Append(", SchemaName: ");
      SchemaName.ToString(tmp403);
    }
    if((TableName != null) && __isset.tableName)
    {
      tmp403.Append(", TableName: ");
      TableName.ToString(tmp403);
    }
    if((ColumnName != null) && __isset.columnName)
    {
      tmp403.Append(", ColumnName: ");
      ColumnName.ToString(tmp403);
    }
    tmp403.Append(')');
    return tmp403.ToString();
  }
}

