/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class TGetDelegationTokenResp : TBase
{
  private string _delegationToken;

  public TStatus Status { get; set; }

  public string DelegationToken
  {
    get
    {
      return _delegationToken;
    }
    set
    {
      __isset.delegationToken = true;
      this._delegationToken = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool delegationToken;
  }

  public TGetDelegationTokenResp()
  {
  }

  public TGetDelegationTokenResp(TStatus @status) : this()
  {
    this.Status = @status;
  }

  public TGetDelegationTokenResp DeepCopy()
  {
    var tmp495 = new TGetDelegationTokenResp()
    if((Status != null))
    {
      tmp495.Status = (TStatus)this.Status.DeepCopy();
    }
    if((DelegationToken != null) && __isset.delegationToken)
    {
      tmp495.DelegationToken = this.DelegationToken;
    }
    tmp495.__isset.delegationToken = this.__isset.delegationToken;
    return tmp495;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_status = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              Status = new TStatus();
              await Status.ReadAsync(iprot, cancellationToken);
              isset_status = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              DelegationToken = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_status)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp496 = new TStruct("TGetDelegationTokenResp");
      await oprot.WriteStructBeginAsync(tmp496, cancellationToken);
      var tmp497 = new TField();
      if((Status != null))
      {
        tmp497.Name = "status";
        tmp497.Type = TType.Struct;
        tmp497.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp497, cancellationToken);
        await Status.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((DelegationToken != null) && __isset.delegationToken)
      {
        tmp497.Name = "delegationToken";
        tmp497.Type = TType.String;
        tmp497.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp497, cancellationToken);
        await oprot.WriteStringAsync(DelegationToken, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is TGetDelegationTokenResp other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(Status, other.Status)
      && ((__isset.delegationToken == other.__isset.delegationToken) && ((!__isset.delegationToken) || (global::System.Object.Equals(DelegationToken, other.DelegationToken))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((Status != null))
      {
        hashcode = (hashcode * 397) + Status.GetHashCode();
      }
      if((DelegationToken != null) && __isset.delegationToken)
      {
        hashcode = (hashcode * 397) + DelegationToken.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp498 = new StringBuilder("TGetDelegationTokenResp(");
    if((Status != null))
    {
      tmp498.Append(", Status: ");
      Status.ToString(tmp498);
    }
    if((DelegationToken != null) && __isset.delegationToken)
    {
      tmp498.Append(", DelegationToken: ");
      DelegationToken.ToString(tmp498);
    }
    tmp498.Append(')');
    return tmp498.ToString();
  }
}

