/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class TGetResultSetMetadataResp : TBase
{
  private TTableSchema _schema;

  public TStatus Status { get; set; }

  public TTableSchema Schema
  {
    get
    {
      return _schema;
    }
    set
    {
      __isset.@schema = true;
      this._schema = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool @schema;
  }

  public TGetResultSetMetadataResp()
  {
  }

  public TGetResultSetMetadataResp(TStatus @status) : this()
  {
    this.Status = @status;
  }

  public TGetResultSetMetadataResp DeepCopy()
  {
    var tmp475 = new TGetResultSetMetadataResp()
    if((Status != null))
    {
      tmp475.Status = (TStatus)this.Status.DeepCopy();
    }
    if((Schema != null) && __isset.@schema)
    {
      tmp475.Schema = (TTableSchema)this.Schema.DeepCopy();
    }
    tmp475.__isset.@schema = this.__isset.@schema;
    return tmp475;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_status = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              Status = new TStatus();
              await Status.ReadAsync(iprot, cancellationToken);
              isset_status = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.Struct)
            {
              Schema = new TTableSchema();
              await Schema.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_status)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp476 = new TStruct("TGetResultSetMetadataResp");
      await oprot.WriteStructBeginAsync(tmp476, cancellationToken);
      var tmp477 = new TField();
      if((Status != null))
      {
        tmp477.Name = "status";
        tmp477.Type = TType.Struct;
        tmp477.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp477, cancellationToken);
        await Status.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Schema != null) && __isset.@schema)
      {
        tmp477.Name = "schema";
        tmp477.Type = TType.Struct;
        tmp477.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp477, cancellationToken);
        await Schema.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is TGetResultSetMetadataResp other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(Status, other.Status)
      && ((__isset.@schema == other.__isset.@schema) && ((!__isset.@schema) || (global::System.Object.Equals(Schema, other.Schema))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((Status != null))
      {
        hashcode = (hashcode * 397) + Status.GetHashCode();
      }
      if((Schema != null) && __isset.@schema)
      {
        hashcode = (hashcode * 397) + Schema.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp478 = new StringBuilder("TGetResultSetMetadataResp(");
    if((Status != null))
    {
      tmp478.Append(", Status: ");
      Status.ToString(tmp478);
    }
    if((Schema != null) && __isset.@schema)
    {
      tmp478.Append(", Schema: ");
      Schema.ToString(tmp478);
    }
    tmp478.Append(')');
    return tmp478.ToString();
  }
}

